### ISSUE TITLE
10d and 30d Power not working

### ISSUE THREAD

**Issue by tm1000** [AlexK-99/companion-module-d-und-b-5d#1]
@AlexK-99 Hi there.

I got it connected (its a little finicky but just needs some work)

The mute toggle, on, off work on all the 10d and 30ds I have

Unfortunately the power on/off/toggle does not work at all.

I'll probably spend some time tonight working on it and see where I get.

Do you know typescript at all?

**Comment by tm1000** [comment]
Also feedbacks don't work at all for anything.

Still this is a very promising start!

**Comment by AlexK-99** [comment]
@tm1000 Hi, yes I know typescript but I am not an accomplished programmer. I do it for fun and because I need it for my work. I wrote the whole thing in effectively 10 minutes including reading the source code of the existing QSYS plugin from d&b. If you want I will add you to the repo.  Have you tried running the check aes70 script I linked to in the companion d&b issue. It should create a file that describes all the functions of the amps. Power/feedback and mute works on my 5d amps so that will be a difference in the functions.

Greetings from Germany 

Alex

**Comment by tm1000** [comment]
Sure you can add me on here. I work with typescript daily so I might change it to typescript if you don't mind. Just wanted to see if you knew it or not

As for your other script I haven't run that yet but I will and get back to you!

**Comment by AlexK-99** [comment]
Just for your information there is a cool tool for AES70/OCA called AES70 Explorer [https://aes70explorer.com/](https://aes70explorer.com/)

**Comment by AlexK-99** [comment]
@tm1000 I have sent you an invitation

**Comment by tm1000** [comment]
@AlexK-99 Thanks! Accepted. 

Here's the output of your aes70 tool

10d msgdata.json:
https://gist.githubusercontent.com/tm1000/6a6a1bc3e2282696a31f5e615c4b115c/raw/97f5642edd683e019ffa1c63183360369c2383ab/10d.json

30d msgdata.json:
https://gist.githubusercontent.com/tm1000/1ae489b2d2b242d4efcf40794bdf9b3b/raw/e1a04f81f59f76f31667451f5de50167ce1337f3/30d.json

**Comment by AlexK-99** [comment]
@tm1000
 Thank you very much that helps me a lot.

I think i found the error why power status can not change the names of the commands are different. I will change it tomorrow it is already too late today. you could of course test if the addon works if you simply make Settings_Box/Settings_PwrOn only Settings_PwrOn in line 60 and 61 in the file main.js. The easiest way is to start ase70 explorer and see what the commands are. if you have time it would be nice if you could take a few photos of the contents of the explorer.

**Comment by tm1000** [comment]
@AlexK-99 out of curiosity I wonder if the OCA changes are different along the same lines as the default ports being different. Which means that since there are only two different ports you and I should be able to resolve most of the issues together.

I played with ase70 explorer a bit earlier and it was working. I will get back to it later today/tonight (I am in the western part of the USA) so we can catchup on this tomorrow

**Comment by AlexK-99** [comment]
@tm1000 While reading the qsys plugin I already realized that there are two ports and if I am not mistaken 3 command configurations

**Comment by tm1000** [comment]
@AlexK-99 I also noticed that the R1 software registers itself into ase70 explorer as well

**Comment by AlexK-99** [comment]
@tm1000 Yes, I noticed that if you want to be fully oca certified, both devices and client must show up via oca

**Comment by AlexK-99** [comment]
@tm1000 hi can you please run the updated version of checkaes70.js again and upload me the 2 files rolemapdata.json and msgdata.json

[https://github.com/AlexK-99/check-aes70/blob/main/checkaes70.js](https://github.com/AlexK-99/check-aes70/blob/main/checkaes70.js)

thanks in advance

**Comment by tm1000** [comment]
@AlexK-99 yes I will run this and get back to you. Havent had time to jump back into this recently

**Comment by AlexK-99** [comment]
@tm1000 Hi the module should actually work now but there are still tests missing for 10d and 30d would it be possible for you to test this?

**Comment by tm1000** [comment]
Yes my boss and I were just talking about this last night. We refer to you as "our German friend" haha. 

We are planning on loading this and working through it

**Comment by AlexK-99** [comment]
@tm1000 If it works I would write to the guys at companion to add us to the bundled modules

**Comment by AlexK-99** [comment]
@tm1000 Hi I have added Amp Preset Recall if you could test it would be really nice

**Comment by WillieDaWonka** [comment]
Hi Alex, I've been using this module at the venue I work at, with 11x 5D's, 1x 30D, 1x DS100. I've only ever used the power feature which since using your latest push, worked like a treat. Keep up the good work! Maybe one day we'll crack R1 control, right down to EQ notches. If you've got anything you'd wish to test with 5D's, I'll try to test them when I've got some downtime.

**Comment by AlexK-99** [comment]
@WillieDaWonka  Hi the project has now moved to companion.

Very good that it works but what exactly do you mean by EQ's and R1.
The amps have the possibility to adjust eq directly without R1 which is a planned feature if you mean that.

**Do you use the module for all amps?**

If you have problems and ideas for new functions
let me know in the new repo!!!
[bitfocus/companion-module-dbaudiotechnik-amps](https://github.com/bitfocus/companion-module-dbaudiotechnik-amps)

**The module will most likely be officially released with companion version 3.5**
