### ISSUE TITLE
Crashing when loaded

### ISSUE THREAD

**Issue by jacksonflynn** [AlexK-99/companion-module-d-und-b-5d#4]
I'm having an issue where when loading the module it's just crashing on startup.
I'm running companion 3.3.1 on MacOS and it's loaded via the "Developer Modules Path" folder
What version of companion have you tested on and what OS
Thanks - J

**Comment by AlexK-99** [comment]
@jacksonflynn I have it running on Windows 10/11 and Linux Ubuntu in version 3.3.1 can you maybe send me the log of the module

**Comment by jacksonflynn** [comment]
Hey @AlexK-99 I'll try on windows tomorrow and let you know if that works, but here is the log
thanks so much for your help!

[module-log-26_08_2024-22_17_27.csv](https://github.com/user-attachments/files/16748518/module-log-26_08_2024-22_17_27.csv)

**Comment by AlexK-99** [comment]
@jacksonflynn Did you run the command "npm install"  to install the dependencies as it is a dev module (to use this command node js must be installed)
